[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend",
  "npm install --prefix admin"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "npm run build --prefix admin"
]

[start]
cmd = "node backend/server.js"

[variables]
NODE_ENV = "production"
