[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install",
  "cd admin && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd admin && npm run build"
]

[start]
cmd = "cd backend && node server.js"

[variables]
NODE_ENV = "production"
